# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2010-2016, Thomas Schikarski, Irene HÃ¶ppner, Andreas Groth
  project: EXT: Shibboleth
  version: 3.0
  release: 3.0.0
...